//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_framework_call_stored_procedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CompanyEntities : DbContext
    {
        public CompanyEntities()
            : base("name=CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<UspGetAllCountries_Result> UspGetAllCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspGetAllCountries_Result>("UspGetAllCountries");
        }
    
        public virtual ObjectResult<string> UspGetCountry(Nullable<int> coutryId)
        {
            var coutryIdParameter = coutryId.HasValue ?
                new ObjectParameter("coutryId", coutryId) :
                new ObjectParameter("coutryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UspGetCountry", coutryIdParameter);
        }
    }
}
