//------------------------------------------------------------------------------
// <auto-generated>
// This is a comment by me (Ahmed Ezzat)
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_change_t4_template_edmx_file.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
